### ISSUE TITLE
Can't select a folder if that contains subfolders and I can't select subfolders without automatically selecting the containing folder

### ISSUE THREAD

**Issue by omnitetranet** [memeller/thunderbird-mark-as-read#1]
As in the title, if you select a folder that contains one or more subfolders, all subfolders become automatically selected.
Also if I want to mark as read all subfolders, but not containing folder, I must create a "dummy folder" to avoid that the container folder will be automatically selected.
I haven't tested if this wrong selection marking also containing folder messages as read. 
I think that adding an extra checkbox named for example "[select-all]" at same level of the subfolders, make the trick.

PS: My emails are automatically routed by the mail server and I've no filters set in thunderbird that sorting messages, therefore I've no options to set messages as read.

Thanks and best regards

**Comment by memeller** [comment]
This was due to the way the tree view component was configured.
You can now # disable the automatic selection of subfolders by unchecking the box below the tree view list - this should allow you to e.g. select the parent folder and leave the subfolders unselected. I've uploaded the updated version to addons.thunderbird.net, it will be available shortly.

**Comment by daCaPo** [comment]
It seems still not possible to select a subfolder without its parent.

**Comment by memeller** [comment]
There is a checkbox that changes the behaviour of the tree selection
![obraz](https://github.com/memeller/thunderbird-mark-as-read/assets/1408352/ee23b670-cdb9-45bd-9767-814afb013331)
This works both ways - if the checkbox is checked, then selecting the parent folder will also select the subfolder, but selecting the subfolder will also select the parent folder. I have just checked and everything seems to work fine - I can easily select a single subfolder (without selecting parent folder) when the behaviour checkbox is not checked.
