### ISSUE TITLE
Maximum of 100 emails marked as read on startup

### ISSUE THREAD

**Issue by ChadThackray** [memeller/thunderbird-mark-as-read#7]
When I launch Thunderbird with this extension, only 100 files are marked as read from the folders I've selected. 

If I re-launch another 100 will be marked read etc.

Is this behavior intentional? In my case I activated the addon on a folder with 10k unread emails and it's slowly going down every time I re-open. 

Not sure if this would also apply if you received more than 100 emails since you last opened the client or if it's just a one time backlog problem. 

Thank you for this awesome plugin!

**Comment by memeller** [comment]
You are right, I forgot that when querying folders for messages, you only get the first 100 messages and have to check if there are more. 
This behavior of the extension - only tagging the first 100 messages - was obviously unintentional and I have updated the code (#8) to include all messages. Thanks for noticing the problem and describing it in such detail.
